
with src_immi as (
  select * from {{ ref('src_immigration') }}
)

select 
      distinct i94port as code,
      case i94port
      when 'ALC'	then	'ALCAN, AK             '
       when 'ANC'	then	'ANCHORAGE, AK         '
       when 'BAR'	then	'BAKER AAF - BAKER ISLAND, AK'
       when 'DAC'	then	'DALTONS CACHE, AK     '
       when 'PIZ'	then	'DEW STATION PT LAY DEW, AK'
       when 'DTH'	then	'DUTCH HARBOR, AK      '
       when 'EGL'	then	'EAGLE, AK             '
       when 'FRB'	then	'FAIRBANKS, AK         '
       when 'HOM'	then	'HOMER, AK             '           
       when 'HYD'	then	'HYDER, AK             '
       when 'JUN'	then	'JUNEAU, AK            '
       when '5KE'	then	'KETCHIKAN, AK'
       when 'KET'	then	'KETCHIKAN, AK         '
       when 'MOS'	then	'MOSES POINT INTERMEDIATE, AK'
       when 'NIK'	then	'NIKISKI, AK           '
       when 'NOM'	then	'NOM, AK               '
       when 'PKC'	then	'POKER CREEK, AK       '
       when 'ORI'	then	'PORT LIONS SPB, AK'
       when 'SKA'	then	'SKAGWAY, AK           '
       when 'SNP'	then	'ST. PAUL ISLAND, AK'
       when 'TKI'	then	'TOKEEN, AK'
       when 'WRA'	then	'WRANGELL, AK          '
       when 'HSV'	then	'MADISON COUNTY - HUNTSVILLE, AL'
       when 'MOB'	then	'MOBILE, AL            '
       when 'LIA'	then	'LITTLE ROCK, AR (BPS)'
       when 'ROG'	then	'ROGERS ARPT, AR'
       when 'DOU'	then	'DOUGLAS, AZ           '
       when 'LUK'	then	'LUKEVILLE, AZ         '
       when 'MAP'	then	'MARIPOSA AZ           '
       when 'NAC'	then	'NACO, AZ              '
       when 'NOG'	then	'NOGALES, AZ           '
       when 'PHO'	then	'PHOENIX, AZ           '
       when 'POR'	then	'PORTAL, AZ'
       when 'SLU'	then	'SAN LUIS, AZ          '
       when 'SAS'	then	'SASABE, AZ            '
       when 'TUC'	then	'TUCSON, AZ            '
       when 'YUI'	then	'YUMA, AZ              ' 
       when 'AND'	then	'ANDRADE, CA           '
       when 'BUR'	then	'BURBANK, CA'
       when 'CAL'	then	'CALEXICO, CA          '
       when 'CAO'	then	'CAMPO, CA             ' 
       when 'FRE'	then	'FRESNO, CA            '
       when 'ICP'	then	'IMPERIAL COUNTY, CA   '
       when 'LNB'	then	'LONG BEACH, CA         '
       when 'LOS'	then	'LOS ANGELES, CA       '
       when 'BFL'	then	'MEADOWS FIELD - BAKERSFIELD, CA'
       when 'OAK'	then	'OAKLAND, CA ' 
       when 'ONT'	then	'ONTARIO, CA'
       when 'OTM'	then	'OTAY MESA, CA          '
       when 'BLT'	then	'PACIFIC, HWY. STATION, CA '
       when 'PSP'	then	'PALM SPRINGS, CA'
       when 'SAC'	then	'SACRAMENTO, CA        '
       when 'SLS'	then	'SALINAS, CA (BPS)'
       when 'SDP'	then	'SAN DIEGO, CA'
       when 'SFR'	then	'SAN FRANCISCO, CA     '
       when 'SNJ'	then	'SAN JOSE, CA          '
       when 'SLO'	then	'SAN LUIS OBISPO, CA   '
       when 'SLI'	then	'SAN LUIS OBISPO, CA (BPS)'
       when 'SPC'	then	'SAN PEDRO, CA         '
       when 'SYS'	then	'SAN YSIDRO, CA        '
       when 'SAA'	then	'SANTA ANA, CA         '
       when 'STO'	then	'STOCKTON, CA (BPS)'
       when 'TEC'	then	'TECATE, CA            '
       when 'TRV'	then	'TRAVIS-AFB, CA        '
       when 'APA'	then	'ARAPAHOE COUNTY, CO'
       when 'ASE'	then	'ASPEN, CO #ARPT'
       when 'COS'	then	'COLORADO SPRINGS, CO'
       when 'DEN'	then	'DENVER, CO            '
       when 'DRO'	then	'LA PLATA - DURANGO, CO'
       when 'BDL'	then	'BRADLEY INTERNATIONAL, CT'
       when 'BGC'	then	'BRIDGEPORT, CT        '
       when 'GRT'	then	'GROTON, CT            '
       when 'HAR'	then	'HARTFORD, CT          '
       when 'NWH'	then	'NEW HAVEN, CT         '
       when 'NWL'	then	'NEW LONDON, CT        '
       when 'TST'	then	'NEWINGTON DATA CENTER TEST, CT'
       when 'WAS'	then	'WASHINGTON DC         '
       when 'DOV'	then	'DOVER AFB, DE'
       when 'DVD'	then	'DOVER-AFB, DE         '
       when 'WLL'	then	'WILMINGTON, DE        '
       when 'BOC'	then	'BOCAGRANDE, FL        '
       when 'SRQ'	then	'BRADENTON - SARASOTA, FL'
       when 'CAN'	then	'CAPE CANAVERAL, FL    '
       when 'DAB'	then	'DAYTONA BEACH INTERNATIONAL, FL'
       when 'FRN'	then	'FERNANDINA, FL        '
       when 'FTL'	then	'FORT LAUDERDALE, FL   '
       when 'FMY'	then	'FORT MYERS, FL        '
       when 'FPF'	then	'FORT PIERCE, FL       '
       when 'HUR'	then	'HURLBURT FIELD, FL'
       when 'GNV'	then	'J R ALISON MUNI - GAINESVILLE, FL'
       when 'JAC'	then	'JACKSONVILLE, FL      '
       when 'KEY'	then	'KEY WEST, FL          '
       when 'LEE'	then	'LEESBURG MUNICIPAL AIRPORT, FL'
       when 'MLB'	then	'MELBOURNE, FL'
       when 'MIA'	then	'MIAMI, FL             '
       when 'APF'	then	'NAPLES, FL #ARPT'
       when 'OPF'	then	'OPA LOCKA, FL'
       when 'ORL'	then	'ORLANDO, FL           '
       when 'PAN'	then	'PANAMA CITY, FL       '
       when 'PEN'	then	'PENSACOLA, FL         '
       when 'PCF'	then	'PORT CANAVERAL, FL    '
       when 'PEV'	then	'PORT EVERGLADES, FL   '
       when 'PSJ'	then	'PORT ST JOE, FL       '
       when 'SFB'	then	'SANFORD, FL           '
       when 'SGJ'	then	'ST AUGUSTINE ARPT, FL'
       when 'SAU'	then	'ST AUGUSTINE, FL      '
       when 'FPR'	then	'ST LUCIE COUNTY, FL'
       when 'SPE'	then	'ST PETERSBURG, FL     '
       when 'TAM'	then	'TAMPA, FL             '
       when 'WPB'	then	'WEST PALM BEACH, FL   '
       when 'ATL'	then	'ATLANTA, GA           '
       when 'BRU'	then	'BRUNSWICK, GA         '
       when 'AGS'	then	'BUSH FIELD - AUGUSTA, GA'
       when 'SAV'	then	'SAVANNAH, GA          '
       when 'AGA'	then	'AGANA, GU             '
       when 'HHW'	then	'HONOLULU, HI          '
       when 'OGG'	then	'KAHULUI - MAUI, HI'
       when 'KOA'	then	'KEAHOLE-KONA, HI      '
       when 'LIH'	then	'LIHUE, HI             '
       when 'CID'	then	'CEDAR RAPIDS/IOWA CITY, IA'
       when 'DSM'	then	'DES MOINES, IA'
       when 'BOI'	then	'AIR TERM. (GOWEN FLD) BOISE, ID'
       when 'EPI'	then	'EASTPORT, ID          '
       when 'IDA'	then	'FANNING FIELD - IDAHO FALLS, ID'
       when 'PTL'	then	'PORTHILL, ID          '
       when 'SPI'	then	'CAPITAL - SPRINGFIELD, IL'
       when 'CHI'	then	'CHICAGO, IL           '
       when 'DPA'	then	'DUPAGE COUNTY, IL'
       when 'PIA'	then	'GREATER PEORIA, IL'
       when 'RFD'	then	'GREATER ROCKFORD, IL'
       when 'UGN'	then	'MEMORIAL - WAUKEGAN, IL'
       when 'GAR'	then	'GARY, IN              '
       when 'HMM'	then	'HAMMOND, IN           '
       when 'INP'	then	'INDIANAPOLIS, IN      '
       when 'MRL'	then	'MERRILLVILLE, IN      '
       when 'SBN'	then	'SOUTH BEND, IN'
       when 'ICT'	then	'MID-CONTINENT - WITCHITA, KS'
       when 'LEX'	then	'BLUE GRASS - LEXINGTON, KY'
       when 'LOU'	then	'LOUISVILLE, KY        '
       when 'BTN'	then	'BATON ROUGE, LA       '
       when 'LKC'	then	'LAKE CHARLES, LA      '
       when 'LAK'	then	'LAKE CHARLES, LA (BPS)'
       when 'MLU'	then	'MONROE, LA'
       when 'MGC'	then	'MORGAN CITY, LA       '
       when 'NOL'	then	'NEW ORLEANS, LA       '
       when 'BOS'	then	'BOSTON, MA            '
       when 'GLO'	then	'GLOUCESTER, MA        '
       when 'BED'	then	'HANSCOM FIELD - BEDFORD, MA'
       when 'LYN'	then	'LYNDEN, WA            '
       when 'ADW'	then	'ANDREWS AFB, MD'
       when 'BAL'	then	'BALTIMORE, MD         '
       when 'MKG'	then	'MUSKEGON, MD'
       when 'PAX'	then	'PATUXENT RIVER, MD    '
       when 'BGM'	then	'BANGOR, ME            '
       when 'BOO'	then	'BOOTHBAY HARBOR, ME   '
       when 'BWM'	then	'BRIDGEWATER, ME       '
       when 'BCK'	then	'BUCKPORT, ME          '
       when 'CLS'	then	'CALAIS, ME   '
       when 'CRB'	then	'CARIBOU, ME           '
       when 'COB'	then	'COBURN GORE, ME       '
       when 'EST'	then	'EASTCOURT, ME         '
       when 'EPT'	then	'EASTPORT MUNICIPAL, ME'
       when 'EPM'	then	'EASTPORT, ME          '
       when 'FOR'	then	'FOREST CITY, ME       '
       when 'FTF'	then	'FORT FAIRFIELD, ME    '
       when 'FTK'	then	'FORT KENT, ME         '
       when 'HML'	then	'HAMIIN, ME            '
       when 'HTM'	then	'HOULTON, ME           '
       when 'JKM'	then	'JACKMAN, ME           '
       when 'KAL'	then	'KALISPEL, MT          '
       when 'LIM'	then	'LIMESTONE, ME         '
       when 'LUB'	then	'LUBEC, ME             '
       when 'MAD'	then	'MADAWASKA, ME         '
       when 'POM'	then	'PORTLAND, ME          '
       when 'RGM'	then	'RANGELEY, ME (BPS)'
       when 'SBR'	then	'SOUTH BREWER, ME      '
       when 'SRL'	then	'ST AURELIE, ME        '
       when 'SPA'	then	'ST PAMPILE, ME        '
       when 'VNB'	then	'VAN BUREN, ME         '
       when 'VCB'	then	'VANCEBORO, ME         '
       when 'AGN'	then	'ALGONAC, MI           '
       when 'ALP'	then	'ALPENA, MI            '
       when 'BCY'	then	'BAY CITY, MI          '
       when 'DET'	then	'DETROIT, MI           '
       when 'GRP'	then	'GRAND RAPIDS, MI'
       when 'GRO'	then	'GROSSE ISLE, MI       '
       when 'ISL'	then	'ISLE ROYALE, MI       '
       when 'MRC'	then	'MARINE CITY, MI       '
       when 'MRY'	then	'MARYSVILLE, MI        '
       when 'PTK'	then	'OAKLAND COUNTY - PONTIAC, MI'
       when 'PHU'	then	'PORT HURON, MI        '
       when 'RBT'	then	'ROBERTS LANDING, MI   '
       when 'SAG'	then	'SAGINAW, MI           '
       when 'SSM'	then	'SAULT STE. MARIE, MI  '
       when 'SCL'	then	'ST CLAIR, MI          '
       when 'YIP'	then	'WILLOW RUN - YPSILANTI, MI'
       when 'BAU'	then	'BAUDETTE, MN          '
       when 'CAR'	then	'CARIBOU MUNICIPAL AIRPORT, MN'
       when 'GTF'	then	'Collapsed into INT, MN'
       when 'INL'	then	'Collapsed into INT, MN'
       when 'CRA'	then	'CRANE LAKE, MN        '
       when 'MIC'	then	'CRYSTAL MUNICIPAL AIRPORT, MN'
       when 'DUL'	then	'DULUTH, MN            '
       when 'ELY'	then	'ELY, MN               '
       when 'GPM'	then	'GRAND PORTAGE, MN     '
       when 'SVC'	then	'GRANT COUNTY - SILVER CITY, MN'
       when 'INT'	then	'INT''L FALLS, MN      '
       when 'LAN'	then	'LANCASTER, MN         '
       when 'MSP'	then	'MINN./ST PAUL, MN     '
       when 'LIN'	then	'NORTHERN SVC CENTER, MN   '
       when 'NOY'	then	'NOYES, MN             '
       when 'PIN'	then	'PINE CREEK, MN        '
       when '48Y'	then	'PINECREEK BORDER ARPT, MN'
       when 'RAN'	then	'RAINER, MN            '
       when 'RST'	then	'ROCHESTER, MN'
       when 'ROS'	then	'ROSEAU, MN            '
       when 'SPM'	then	'ST PAUL, MN           '
       when 'WSB'	then	'WARROAD INTL, SPB, MN'
       when 'WAR'	then	'WARROAD, MN           '
       when 'KAN'	then	'KANSAS CITY, MO       '
       when 'SGF'	then	'SPRINGFIELD-BRANSON, MO'
       when 'STL'	then	'ST LOUIS, MO          '
       when 'WHI'	then	'WHITETAIL, MT         '
       when 'WHM'	then	'WILD HORSE, MT        '
       when 'GPT'	then	'BILOXI REGIONAL, MS'
       when 'GTR'	then	'GOLDEN TRIANGLE LOWNDES CNTY, MS'
       when 'GUL'	then	'GULFPORT, MS          '
       when 'PAS'	then	'PASCAGOULA, MS        '
       when 'JAN'	then	'THOMPSON FIELD - JACKSON, MS'
       when 'BIL'	then	'BILLINGS, MT          '
       when 'BTM'	then	'BUTTE, MT             '
       when 'CHF'	then	'CHIEF MT, MT          '
       when 'CTB'	then	'CUT BANK MUNICIPAL, MT'
       when 'CUT'	then	'CUT BANK, MT          '
       when 'DLB'	then	'DEL BONITA, MT        '
       when 'EUR'	then	'EUREKA, MT (BPS)'
       when 'BZN'	then	'GALLATIN FIELD - BOZEMAN, MT'
       when 'FCA'	then	'GLACIER NATIONAL PARK, MT'
       when 'GGW'	then	'GLASGOW, MT           '
       when 'GRE'	then	'GREAT FALLS, MT       '
       when 'HVR'	then	'HAVRE, MT             '
       when 'HEL'	then	'HELENA, MT            '
       when 'LWT'	then	'LEWISTON, MT          '
       when 'MGM'	then	'MORGAN, MT            '
       when 'OPH'	then	'OPHEIM, MT            '
       when 'PIE'	then	'PIEGAN, MT            '
       when 'RAY'	then	'RAYMOND, MT           '
       when 'ROO'	then	'ROOSVILLE, MT         '
       when 'SCO'	then	'SCOBEY, MT            '
       when 'SWE'	then	'SWEETGTASS, MT        '
       when 'TRL'	then	'TRIAL CREEK, MT       '
       when 'TUR'	then	'TURNER, MT            '
       when 'WCM'	then	'WILLOW CREEK, MT      '
       when 'CLT'	then	'CHARLOTTE, NC         '
       when 'FAY'	then	'FAYETTEVILLE, NC'
       when 'MRH'	then	'MOREHEAD CITY, NC     '
       when 'FOP'	then	'MORRIS FIELDS AAF, NC'
       when 'GSO'	then	'PIEDMONT TRIAD INTL AIRPORT, NC'
       when 'RDU'	then	'RALEIGH/DURHAM, NC    '
       when 'SSC'	then	'SHAW AFB - SUMTER, NC'
       when 'WIL'	then	'WILMINGTON, NC        '
       when 'AMB'	then	'AMBROSE, ND           '
       when 'ANT'	then	'ANTLER, ND            '
       when 'CRY'	then	'CARBURY, ND           '
       when 'DNS'	then	'DUNSEITH, ND          '
       when 'FAR'	then	'FARGO, ND             '
       when 'FRT'	then	'FORTUNA, ND           '
       when 'GRF'	then	'GRAND FORKS, ND       '
       when 'HNN'	then	'HANNAH, ND            '
       when 'HNS'	then	'HANSBORO, ND          '
       when 'MAI'	then	'MAIDA, ND             '
       when 'MND'	then	'MINOT, ND             '
       when 'NEC'	then	'NECHE, ND             '
       when 'NOO'	then	'NOONAN, ND            '
       when 'NRG'	then	'NORTHGATE, ND         '
       when 'PEM'	then	'PEMBINA, ND           '
       when 'SAR'	then	'SARLES, ND            '
       when 'SHR'	then	'SHERWOOD, ND          '
       when 'SJO'	then	'ST JOHN, ND           '
       when 'WAL'	then	'WALHALLA, ND          '
       when 'WHO'	then	'WESTHOPE, ND          '
       when 'WND'	then	'WILLISTON, ND         '
       when 'OMA'	then	'OMAHA, NE             '
       when 'LEB'	then	'LEBANON, NH           '
       when 'MHT'	then	'MANCHESTER, NH'
       when 'PNH'	then	'PITTSBURG, NH         '
       when 'PSM'	then	'PORTSMOUTH, NH        '
       when 'BYO'	then	'BAYONNE, NJ           '
       when 'CNJ'	then	'CAMDEN, NJ            '
       when 'HOB'	then	'HOBOKEN, NJ           '
       when 'JER'	then	'JERSEY CITY, NJ       '
       when 'WRI'	then	'MC GUIRE AFB - WRIGHTSOWN, NJ'
       when 'MMU'	then	'MORRISTOWN, NJ'
       when 'NEW'	then	'NEWARK/TETERBORO, NJ  '
       when 'PER'	then	'PERTH AMBOY, NJ       '
       when 'ACY'	then	'POMONA FIELD - ATLANTIC CITY, NJ'
       when 'ALA'	then	'ALAMAGORDO, NM (BPS)'
       when 'ABQ'	then	'ALBUQUERQUE, NM       '
       when 'ANP'	then	'ANTELOPE WELLS, NM    '
       when 'CRL'	then	'CARLSBAD, NM          '
       when 'COL'	then	'COLUMBUS, NM          '
       when 'CDD'	then	'CRANE LAKE - ST. LOUIS CNTY, NM'
       when 'DNM'	then	'DEMING, NM (BPS)'
       when 'LAS'	then	'LAS CRUCES, NM        '
       when 'LOB'	then	'LORDSBURG, NM (BPS)'
       when 'RUI'	then	'RUIDOSO, NM'
       when 'STR'	then	'SANTA TERESA, NM      '
       when 'RNO'	then	'CANNON INTL - RENO/TAHOE, NV'
       when 'FLX'	then	'FALLON MUNICIPAL AIRPORT, NV'
       when 'LVG'	then	'LAS VEGAS, NV         '
       when 'REN'	then	'RENO, NV              '
       when 'ALB'	then	'ALBANY, NY            '
       when 'AXB'	then	'ALEXANDRIA BAY, NY    '
       when 'BUF'	then	'BUFFALO, NY           '
       when 'CNH'	then	'CANNON CORNERS, NY'
       when 'CAP'	then	'CAPE VINCENT, NY      '
       when 'CHM'	then	'CHAMPLAIN, NY         '
       when 'CHT'	then	'CHATEAUGAY, NY        '
       when 'CLA'	then	'CLAYTON, NY           '
       when 'FTC'	then	'FORT COVINGTON, NY    '
       when 'LAG'	then	'LA GUARDIA, NY        '
       when 'LEW'	then	'LEWISTON, NY          '
       when 'MAS'	then	'MASSENA, NY           '
       when 'MAG'	then	'MCGUIRE AFB, NY       '
       when 'MOO'	then	'MOORES, NY            '
       when 'MRR'	then	'MORRISTOWN, NY        '
       when 'NYC'	then	'NEW YORK, NY          '
       when 'NIA'	then	'NIAGARA FALLS, NY     '
       when 'OGD'	then	'OGDENSBURG, NY        '
       when 'OSW'	then	'OSWEGO, NY            '
       when 'ELM'	then	'REGIONAL ARPT - HORSEHEAD, NY'
       when 'ROC'	then	'ROCHESTER, NY         '
       when 'ROU'	then	'ROUSES POINT, NY      '
       when 'SWF'	then	'STEWART - ORANGE CNTY, NY'
       when 'SYR'	then	'SYRACUSE, NY          '
       when 'THO'	then	'THOUSAND ISLAND BRIDGE, NY'
       when 'TRO'	then	'TROUT RIVER, NY       '
       when 'WAT'	then	'WATERTOWN, NY         '
       when 'HPN'	then	'WESTCHESTER - WHITE PLAINS, NY'
       when 'WRB'	then	'WHIRLPOOL BRIDGE, NY'
       when 'YOU'	then	'YOUNGSTOWN, NY        '
       when 'AKR'	then	'AKRON, OH             '
       when 'ATB'	then	'ASHTABULA, OH         '
       when 'CIN'	then	'CINCINNATI, OH        '
       when 'CLE'	then	'CLEVELAND, OH         '
       when 'CLM'	then	'COLUMBUS, OH          '
       when 'LOR'	then	'LORAIN, OH            '
       when 'MBO'	then	'MARBLE HEADS, OH      '
       when 'SDY'	then	'SANDUSKY, OH          '
       when 'TOL'	then	'TOLEDO, OH            '
       when 'OKC'	then	'OKLAHOMA CITY, OK     '
       when 'TUL'	then	'TULSA, OK'
       when 'AST'	then	'ASTORIA, OR           '
       when 'COO'	then	'COOS BAY, OR          '
       when 'HIO'	then	'HILLSBORO, OR'
       when 'MED'	then	'MEDFORD, OR           '
       when 'NPT'	then	'NEWPORT, OR           '
       when 'POO'	then	'PORTLAND, OR          '
       when 'PUT'	then	'PUT-IN-BAY, OH        '
       when 'RDM'	then	'ROBERTS FIELDS - REDMOND, OR'
       when 'ERI'	then	'ERIE, PA              '
       when 'MDT'	then	'HARRISBURG, PA'
       when 'HSB'	then	'HARRISONBURG, PA      '
       when 'PHI'	then	'PHILADELPHIA, PA      '
       when 'PIT'	then	'PITTSBURG, PA         '
       when 'AGU'	then	'AGUADILLA, PR         '
       when 'BQN'	then	'BORINQUEN - AGUADILLO, PR'
       when 'JCP'	then	'CULEBRA - BENJAMIN RIVERA, PR'
       when 'ENS'	then	'ENSENADA, PR          '
       when 'FAJ'	then	'FAJARDO, PR           '
       when 'HUM'	then	'HUMACAO, PR           '
       when 'JOB'	then	'JOBOS, PR             '
       when 'MAY'	then	'MAYAGUEZ, PR          '
       when 'PON'	then	'PONCE, PR             '
       when 'PSE'	then	'PONCE-MERCEDITA, PR'
       when 'SAJ'	then	'SAN JUAN, PR          '
       when 'VQS'	then	'VIEQUES-ARPT, PR'
       when 'PRO'	then	'PROVIDENCE, RI        '
       when 'PVD'	then	'THEODORE FRANCIS - WARWICK, RI'
       when 'CHL'	then	'CHARLESTON, SC        '
       when 'CAE'	then	'COLUMBIA, SC #ARPT'
       when 'GEO'	then	'GEORGETOWN, SC        '
       when 'GSP'	then	'GREENVILLE, SC'
       when 'GRR'	then	'GREER, SC'
       when 'MYR'	then	'MYRTLE BEACH, SC'
       when 'SPF'	then	'BLACK HILLS, SPEARFISH, SD'
       when 'HON'	then	'HOWES REGIONAL ARPT - HURON, SD'
       when 'SAI'	then	'SAIPAN, SPN           '
       when 'TYS'	then	'MC GHEE TYSON - ALCOA, TN'
       when 'MEM'	then	'MEMPHIS, TN           '
       when 'NSV'	then	'NASHVILLE, TN         '
       when 'TRI'	then	'TRI CITY ARPT, TN'
       when 'ADS'	then	'ADDISON AIRPORT- ADDISON, TX'
       when 'ADT'	then	'AMISTAD DAM, TX       '
       when 'ANZ'	then	'ANZALDUAS, TX'
       when 'AUS'	then	'AUSTIN, TX            '
       when 'BEA'	then	'BEAUMONT, TX          '
       when 'BBP'	then	'BIG BEND PARK, TX (BPS)'
       when 'SCC'	then	'BP SPEC COORD. CTR, TX'
       when 'BTC'	then	'BP TACTICAL UNIT, TX  ' 
       when 'BOA'	then	'BRIDGE OF AMERICAS, TX'
       when 'BRO'	then	'BROWNSVILLE, TX       '
       when 'CRP'	then	'CORPUS CHRISTI, TX    '
       when 'DAL'	then	'DALLAS, TX            '
       when 'DLR'	then	'DEL RIO, TX           '
       when 'DNA'	then	'DONNA, TX'
       when 'EGP'	then	'EAGLE PASS, TX        '
       when 'ELP'	then	'EL PASO, TX           '
       when 'FAB'	then	'FABENS, TX            '
       when 'FAL'	then	'FALCON HEIGHTS, TX    '
       when 'FTH'	then	'FORT HANCOCK, TX      '
       when 'AFW'	then	'FORT WORTH ALLIANCE, TX'
       when 'FPT'	then	'FREEPORT, TX          '
       when 'GAL'	then	'GALVESTON, TX         '
       when 'HLG'	then	'HARLINGEN, TX         '
       when 'HID'	then	'HIDALGO, TX           '
       when 'HOU'	then	'HOUSTON, TX           '
       when 'SGR'	then	'HULL FIELD, SUGAR LAND ARPT, TX'
       when 'LLB'	then	'JUAREZ-LINCOLN BRIDGE, TX'
       when 'LCB'	then	'LAREDO COLUMBIA BRIDGE, TX'
       when 'LRN'	then	'LAREDO NORTH, TX      '
       when 'LAR'	then	'LAREDO, TX            '
       when 'LSE'	then	'LOS EBANOS, TX        '
       when 'IND'	then	'LOS INDIOS, TX'
       when 'LOI'	then	'LOS INDIOS, TX        '
       when 'MRS'	then	'MARFA, TX (BPS)'
       when 'MCA'	then	'MCALLEN, TX           '
       when 'MAF'	then	'ODESSA REGIONAL, TX'
       when 'PDN'	then	'PASO DEL NORTE,TX     '
       when 'PBB'	then	'PEACE BRIDGE, NY      '
       when 'PHR'	then	'PHARR, TX             '
       when 'PAR'	then	'PORT ARTHUR, TX       '
       when 'ISB'	then	'PORT ISABEL, TX       '
       when 'POE'	then	'PORT OF EL PASO, TX   '
       when 'PRE'	then	'PRESIDIO, TX          '
       when 'PGR'	then	'PROGRESO, TX          '
       when 'RIO'	then	'RIO GRANDE CITY, TX   '
       when 'ROM'	then	'ROMA, TX              '
       when 'SNA'	then	'SAN ANTONIO, TX       '
       when 'SNN'	then	'SANDERSON, TX         '
       when 'VIB'	then	'VETERAN INTL BRIDGE, TX'
       when 'YSL'	then	'YSLETA, TX            '
       when 'CHA'	then	'CHARLOTTE AMALIE, VI  '
       when 'CHR'	then	'CHRISTIANSTED, VI     '
       when 'CRU'	then	'CRUZ BAY, ST JOHN, VI '
       when 'FRK'	then	'FREDERIKSTED, VI      '
       when 'STT'	then	'ST THOMAS, VI         '
       when 'LGU'	then	'CACHE AIRPORT - LOGAN, UT'
       when 'SLC'	then	'SALT LAKE CITY, UT    '
       when 'CHO'	then	'ALBEMARLE CHARLOTTESVILLE, VA'
       when 'DAA'	then	'DAVISON AAF - FAIRFAX CNTY, VA'
       when 'HOP'	then	'HOPEWELL, VA          '
       when 'HEF'	then	'MANASSAS, VA #ARPT'
       when 'NWN'	then	'NEWPORT, VA           '
       when 'NOR'	then	'NORFOLK, VA           '
       when 'RCM'	then	'RICHMOND, VA          '
       when 'ABS'	then	'ALBURG SPRINGS, VT    '
       when 'ABG'	then	'ALBURG, VT            '
       when 'BEB'	then	'BEEBE PLAIN, VT       '
       when 'BEE'	then	'BEECHER FALLS, VT     '
       when 'BRG'	then	'BURLINGTON, VT        '
       when 'CNA'	then	'CANAAN, VT            '
       when 'DER'	then	'DERBY LINE, VT (I-91) '
       when 'DLV'	then	'DERBY LINE, VT (RT. 5)'
       when 'ERC'	then	'EAST RICHFORD, VT     '
       when 'HIG'	then	'HIGHGATE SPRINGS, VT  '
       when 'MOR'	then	'MORSES LINE, VT       '
       when 'NPV'	then	'NEWPORT, VT           '
       when 'NRT'	then	'NORTH TROY, VT        '
       when 'NRN'	then	'NORTON, VT            '
       when 'PIV'	then	'PINNACLE ROAD, VT     '
       when 'RIF'	then	'RICHFORT, VT          '
       when 'STA'	then	'ST ALBANS, VT         '
       when 'SWB'	then	'SWANTON, VT (BP - SECTOR HQ)'
       when 'WBE'	then	'WEST BERKSHIRE, VT    '
       when 'ABE'	then	'ABERDEEN, WA          '
       when 'ANA'	then	'ANACORTES, WA         '
       when 'BEL'	then	'BELLINGHAM, WA        '
       when 'BLI'	then	'BELLINGHAM, WASHINGTON #INTL'
       when 'BLA'	then	'BLAINE, WA            '
       when 'BWA'	then	'BOUNDARY, WA          '
       when 'CUR'	then	'CURLEW, WA (BPS)'
       when 'DVL'	then	'DANVILLE, WA          '
       when 'EVE'	then	'EVERETT, WA           '
       when 'FER'	then	'FERRY, WA             '
       when 'FRI'	then	'FRIDAY HARBOR, WA     '
       when 'FWA'	then	'FRONTIER, WA          '
       when 'KLM'	then	'KALAMA, WA            '
       when 'LAU'	then	'LAURIER, WA           '
       when 'LON'	then	'LONGVIEW, WA          '
       when 'MET'	then	'METALINE FALLS, WA    '
       when 'MWH'	then	'MOSES LAKE GRANT COUNTY ARPT, WA'
       when 'NEA'	then	'NEAH BAY, WA          '
       when 'NIG'	then	'NIGHTHAWK, WA         '
       when 'OLY'	then	'OLYMPIA, WA           '
       when 'ORO'	then	'OROVILLE, WA          '
       when 'PWB'	then	'PASCO, WA             '
       when 'PIR'	then	'POINT ROBERTS, WA     '
       when 'PNG'	then	'PORT ANGELES, WA      '
       when 'PTO'	then	'PORT TOWNSEND, WA     '
       when 'SEA'	then	'SEATTLE, WA           '
       when 'SPO'	then	'SPOKANE, WA           '
       when 'SUM'	then	'SUMAS, WA             '
       when 'TAC'	then	'TACOMA, WA            '
       when 'PSC'	then	'TRI-CITIES - PASCO, WA'
       when 'VAN'	then	'VANCOUVER, WA         '
       when 'AGM'	then	'ALGOMA, WI            '
       when 'BAY'	then	'BAYFIELD, WI          '
       when 'GRB'	then	'GREEN BAY, WI         '
       when 'MNW'	then	'MANITOWOC, WI         '
       when 'MIL'	then	'MILWAUKEE, WI         '
       when 'MSN'	then	'TRUAX FIELD - DANE COUNTY, WI'
       when 'CHS'	then	'CHARLESTON, WV        '
       when 'CLK'	then	'CLARKSBURG, WV        '
       when 'BLF'	then	'MERCER COUNTY, WV'
       when 'CSP'	then	'CASPER, WY            '
       when 'XXX'	then	'NOT REPORTED/UNKNOWN  ' 
       when '888'	then	'UNIDENTIFED AIR / SEAPORT'
       when 'UNK'	then	'UNKNOWN POE           '
       when 'CLG'	then	'CALGARY, CANADA       '
       when 'EDA'	then	'EDMONTON, CANADA      '
       when 'YHC'	then	'HAKAI PASS, CANADA'
       when 'HAL'	then	'Halifax, NS, Canada   '
       when 'MON'	then	'MONTREAL, CANADA      '
       when 'OTT'	then	'OTTAWA, CANADA        '
       when 'YXE'	then	'SASKATOON, CANADA'
       when 'TOR'	then	'TORONTO, CANADA       '
       when 'VCV'	then	'VANCOUVER, CANADA     '
       when 'VIC'	then	'VICTORIA, CANADA      '
       when 'WIN'	then	'WINNIPEG, CANADA      '
       when 'AMS'	then	'AMSTERDAM-SCHIPHOL, NETHERLANDS'
       when 'ARB'	then	'ARUBA, NETH ANTILLES  '
       when 'BAN'	then	'BANKOK, THAILAND      '
       when 'BEI'	then	'BEICA #ARPT, ETHIOPIA'
       when 'PEK'	then	'BEIJING CAPITAL INTL, PRC'
       when 'BDA'	then	'KINDLEY FIELD, BERMUDA'
       when 'BOG'	then	'BOGOTA, EL DORADO #ARPT, COLOMBIA'
       when 'EZE'	then	'BUENOS AIRES, MINISTRO PIST, ARGENTINA'
       when 'CUN'	then	'CANCUN, MEXICO'
       when 'CRQ'	then	'CARAVELAS, BA #ARPT, BRAZIL'
       when 'MVD'	then	'CARRASCO, URUGUAY'
       when 'DUB'	then	'DUBLIN, IRELAND       '
       when 'FOU'	then	'FOUGAMOU #ARPT, GABON'
       when 'FBA'	then	'FREEPORT, BAHAMAS      '
       when 'MTY'	then	'GEN M. ESCOBEDO, Monterrey, MX'
       when 'HMO'	then	'GEN PESQUEIRA GARCIA, MX'
       when 'GCM'	then	'GRAND CAYMAN, CAYMAN ISLAND'
       when 'GDL'	then	'GUADALAJARA, MIGUEL HIDAL, MX'
       when 'HAM'	then	'HAMILTON, BERMUDA     '
       when 'ICN'	then	'INCHON, SEOUL KOREA'
       when 'IWA'	then	'INVALID - IWAKUNI, JAPAN'
       when 'CND'	then	'KOGALNICEANU, ROMANIA'
       when 'LAH'	then	'LABUHA ARPT, INDONESIA'
       when 'DUR'	then	'LOUIS BOTHA, SOUTH AFRICA'
       when 'MAL'	then	'MANGOLE ARPT, INDONESIA'
       when 'MDE'	then	'MEDELLIN, COLOMBIA'
       when 'MEX'	then	'JUAREZ INTL, MEXICO CITY, MX'
       when 'LHR'	then	'MIDDLESEX, ENGLAND'
       when 'NBO'	then	'NAIROBI, KENYA        '
       when 'NAS'	then	'NASSAU, BAHAMAS       '
       when 'NCA'	then	'NORTH CAICOS, TURK & CAIMAN'
       when 'PTY'	then	'OMAR TORRIJOS, PANAMA'
       when 'SPV'	then	'PAPUA, NEW GUINEA'
       when 'UIO'	then	'QUITO (MARISCAL SUCR), ECUADOR'
       when 'RIT'	then	'ROME, ITALY           '
       when 'SNO'	then	'SAKON NAKHON #ARPT, THAILAND'
       when 'SLP'	then	'SAN LUIS POTOSI #ARPT, MEXICO'
       when 'SAN'	then	'SAN SALVADOR, EL SALVADOR'
       when 'SRO'	then	'SANTANA RAMOS #ARPT, COLOMBIA'
       when 'GRU'	then	'GUARULHOS INTL, SAO PAULO, BRAZIL'
       when 'SHA'	then	'SHANNON, IRELAND      '
       when 'HIL'	then	'SHILLAVO, ETHIOPIA'
       when 'TOK'	then	'TOROKINA #ARPT, PAPUA, NEW GUINEA'
       when 'VER'	then	'VERACRUZ, MEXICO'
       when 'LGW'	then	'WEST SUSSEX, ENGLAND  '
       when 'ZZZ'	then	'MEXICO Land (Banco de Mexico) '
       when 'CHN'	then	'No PORT Code (CHN)'
       when 'CNC'	then	'CANNON CORNERS, NY'
       when 'MAA'	then	'Abu Dhabi'
       when 'AG0'	then	'MAGNOLIA, AR'
       when 'BHM'	then	'BAR HARBOR, ME'
       when 'BHX'	then	'BIRMINGHAM, AL'
       when 'CAK'	then	'AKRON, OH'
       when 'FOK'	then	'SUFFOLK COUNTY, NY'
       when 'LND'	then	'LANDER, WY'
       when 'MAR'	then	'MARFA, TX'
       when 'MLI'	then	'MOLINE, IL'
       when 'RIV'	then	'RIVERSIDE, CA'
       when 'RME'	then	'ROME, NY'
       when 'VNY'	then	'VAN NUYS, CA'
       when 'YUM'	then	'YUMA, AZ'
       when 'FRG'	then	'Collapsed (FOK) 06/15'
       when 'HRL'	then	'Collapsed (HLG) 06/15'
       when 'ISP'	then	'Collapsed (FOK) 06/15'
       when 'JSJ'	then	'Collapsed (SAJ) 06/15'
       when 'BUS'	then	'Collapsed (BUF) 06/15'
       when 'IAG'	then	'Collapsed (NIA) 06/15'
       when 'PHN'	then	'Collapsed (PHU) 06/15'
       when 'STN'	then	'Collapsed (STR) 06/15'
       when 'VMB'	then	'Collapsed (VNB) 06/15'
       when 'T01'	then	'Collapsed (SEA) 06/15'
       when 'PHF'	then	'No PORT Code (PHF)'
       when 'DRV'	then	'No PORT Code (DRV)'
       when 'FTB'	then	'No PORT Code (FTB)'
       when 'GAC'	then	'No PORT Code (GAC)'
       when 'GMT'	then	'No PORT Code (GMT)'
       when 'JFA'	then	'No PORT Code (JFA)'
       when 'JMZ'	then	'No PORT Code (JMZ)'
       when 'NC8'	then	'No PORT Code (NC8)'
       when 'NYL'	then	'No PORT Code (NYL)'
       when 'OAI'	then	'No PORT Code (OAI)'
       when 'PCW'	then	'No PORT Code (PCW)'
       when 'WA5'	then	'No PORT Code (WAS)'
       when 'WTR'	then	'No PORT Code (WTR)'
       when 'X96'	then	'No PORT Code (X96)'
       when 'XNA'	then	'No PORT Code (XNA)'
       when 'YGF'	then	'No PORT Code (YGF)'
       when '5T6'	then	'No PORT Code (5T6)'
       when '060'	then	'No PORT Code (60)'
       when 'SP0'	then	'No PORT Code (SP0)'
       when 'W55'	then	'No PORT Code (W55)'
       when 'X44'	then	'No PORT Code (X44)'
       when 'AUH'	then	'No PORT Code (AUH)'
       when 'RYY'	then	'No PORT Code (RYY)'
       when 'SUS'	then	'No PORT Code (SUS)'
       when '74S'	then	'No PORT Code (74S)'
       when 'ATW'	then	'No PORT Code (ATW)'
       when 'CPX'	then	'No PORT Code (CPX)'
       when 'MTH'	then	'No PORT Code (MTH)'
       when 'PFN'	then	'No PORT Code (PFN)'
       when 'SCH'	then	'No PORT Code (SCH)'
       when 'ASI'	then	'No PORT Code (ASI)'
       when 'BKF'	then	'No PORT Code (BKF)'
       when 'DAY'	then	'No PORT Code (DAY)'
       when 'Y62'	then	'No PORT Code (Y62)'
       when 'AG'		then	'No PORT Code (AG)'
       when 'BCM'	then	'No PORT Code (BCM)'
       when 'DEC'	then	'No PORT Code (DEC)'
       when 'PLB'	then	'No PORT Code (PLB)'
       when 'CXO'	then	'No PORT Code (CXO)'
       when 'JBQ'	then	'No PORT Code (JBQ)'
       when 'JIG'	then	'No PORT Code (JIG)'
       when 'OGS'	then	'No PORT Code (OGS)'
       when 'TIW'	then	'No PORT Code (TIW)'
       when 'OTS'	then	'No PORT Code (OTS)'
       when 'AMT'	then	'No PORT Code (AMT)'
       when 'EGE'	then	'No PORT Code (EGE)'
       when 'GPI'	then	'No PORT Code (GPI)'
       when 'NGL'	then	'No PORT Code (NGL)'
       when 'OLM'	then	'No PORT Code (OLM)'
       when '.GA'	then	'No PORT Code (.GA)'
       when 'CLX'	then	'No PORT Code (CLX)'
       when 'CP '	then	'No PORT Code (CP)'
       when 'FSC'	then	'No PORT Code (FSC)'
       when 'NK' 	then	'No PORT Code (NK)'
       when 'ADU' 	then	'No PORT Code (ADU)'
       when 'AKT' 	then	'No PORT Code (AKT)'
       when 'LIT' 	then	'No PORT Code (LIT)'
       when 'A2A' 	then	'No PORT Code (A2A)'
       when 'OSN' 	then	'No PORT Code (OSN)'
      end as name
from src_immi
where i94port is not null

